version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-225-110-152.compute-1.amazonaws.com
            port: '5432'
            database: dcq94kd189upj3
            schema: schema.graphql
            user: qfztnykhkajayi
            password: fe3986331bacd7838e12faa8023807ce874e5403288554300c62ffa9b7008d8e
            migrations: true
            ssl: true